config/routes.rb
# == Route Map
#
#      Prefix Verb   URI Pattern                 Controller#Action
#       moons GET    /moons(.:format)            moons#index
#             POST   /moons(.:format)            moons#create
#    new_moon GET    /moons/new(.:format)        moons#new
#   edit_moon GET    /moons/:id/edit(.:format)   moons#edit
#        moon GET    /moons/:id(.:format)        moons#show
#             PATCH  /moons/:id(.:format)        moons#update
#             PUT    /moons/:id(.:format)        moons#update
#             DELETE /moons/:id(.:format)        moons#destroy
#     planets GET    /planets(.:format)          planets#index
#             POST   /planets(.:format)          planets#create
#  new_planet GET    /planets/new(.:format)      planets#new
# edit_planet GET    /planets/:id/edit(.:format) planets#edit
#      planet GET    /planets/:id(.:format)      planets#show
#             PATCH  /planets/:id(.:format)      planets#update
#             PUT    /planets/:id(.:format)      planets#update
#             DELETE /planets/:id(.:format)      planets#destroy
#       users GET    /users(.:format)            users#index
#             POST   /users(.:format)            users#create
#    new_user GET    /users/new(.:format)        users#new
#   edit_user GET    /users/:id/edit(.:format)   users#edit
#        user GET    /users/:id(.:format)        users#show
#             PATCH  /users/:id(.:format)        users#update
#             PUT    /users/:id(.:format)        users#update
#             DELETE /users/:id(.:format)        users#destroy
#

Rails.application.routes.draw do
  root :to => 'pages#home' # same as localhost 3000

  resources :users, :only => [:new, :create]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :moons
  resources :planets
  resources :users


  # post 'planets/:id/edit' => 'planets#add_moon'
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/planet.rb
# == Schema Information
#
# Table name: planets
#
#  id            :integer          not null, primary key
#  name          :text
#  distance_sun  :float
#  radius_orbit  :float
#  radius_planet :float
#  orbit_sun     :float
#  num_moon      :integer
#  image         :text
#  info          :text
#  moon_id       :integer
#  user_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Planet < ApplicationRecord
  has_many :moons
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: [:show, :edit, :update, :destroy]

  # GET /planets
  # GET /planets.json
  def index
    @planets = Planet.all
  end

  # GET /planets/1
  # GET /planets/1.json
  def show
  end

  # GET /planets/new
  def new
    @planet = Planet.new
  end

  # GET /planets/1/edit
  def edit
  end

  # POST /planets
  # POST /planets.json
  def create
    planet = Planet.new(planet_params)

    if params['planet']['image'].nil?
    else
         # perform file upload
         cloudinary = Cloudinary::Uploader.upload( params['planet']['image'])
         planet.image = cloudinary['url']
    end


    respond_to do |format|
      if planet.save
        format.html { redirect_to planet, notice: 'Planet was successfully created.' }
        format.json { render :show, status: :created, location: planet }
      else
        format.html { render :new }
        format.json { render json: planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planets/1
  # PATCH/PUT /planets/1.json
  def update
    if params['planet']['image'].nil?
    else
         # perform file upload
         cloudinary = Cloudinary::Uploader.upload( params['planet']['image'])
         @planet.image = cloudinary['url']
    end
    respond_to do |format|
      if @planet.update(planet_params)
        format.html { redirect_to @planet, notice: 'Planet was successfully updated.' }
        format.json { render :show, status: :ok, location: @planet }
      else
        format.html { render :edit }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planets/1
  # DELETE /planets/1.json
  def destroy
    @planet.destroy
    respond_to do |format|
      format.html { redirect_to planets_url, notice: 'Planet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planet
      @planet = Planet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def planet_params
      params.require(:planet).permit(:name, :distance_sun, :radius_orbit, :radius_planet, :orbit_sun, :num_moon, :info, :moon_id, :user_id)
    end
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/planets/_form.html.erb
<div class="form-style">
  <%= form_with(model: planet, local: true, html: { :multipart => true }) do |form| %>

    <% if planet.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(planet.errors.count, "error") %> prohibited this planet from being saved:</h2>
        <ul>
          <% planet.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.label :name %>
    <%= form.text_field :name, id: :planet_name %>

    <%= form.label :distance_sun %>
    <%= form.number_field :distance_sun, id: :planet_distance_sun %>

    <%= form.label :radius_planet %>
    <%= form.number_field :radius_planet, id: :planet_radius_planet %>

    <%= form.label :orbit_sun %>
    <%= form.number_field :orbit_sun, id: :planet_orbit_sun %>

    <%= form.label :num_moon %>
    <%= form.number_field :num_moon, id: :planet_num_moon %>

    <%= form.label :image %><br>
    <%= form.file_field :image %>

    <%= form.label :info %>
    <%= form.text_area :info, :autofocus => true,  :class => 'notes-text-area'  %>

    <%= form.submit %>
  <% end %>
</div><!-- END form-style DIV -->

app/views/planets/edit.html.erb
<h1>Editing Planet</h1>

<%= render 'form', planet: @planet %>

<div class="controls">
  <%= link_to 'Show', @planet %> |
  <%= link_to 'Back', planets_path %>
</div>

app/views/planets/index.html.erb
<p id="notice"><%= notice %></p>

<h2 id="small-planets-h2">Planets</h2>
<div id="solar-animation">
  <%= content_tag :div, id: "solar", data: {planets: @planets} do %>
  <% end %>
</div>
<script>
  // $(window).scroll(function(){
  // let threshold = 800; // number of pixels before bottom of page that you want to start fading
  // var op = (($(document).height() - $(window).height()) - $(window).scrollTop()) / threshold;
  // if( op <= 0 ){
  //   $(".dg.a ").hide();
  // } else {
  //   $(".dg.a").show();
  // }
  // $(".dg.a").css("opacity", op );
  // });
</script>

<aside class="planet-list">
  <% @planets.each do |planet| %>
   <p id="planet-index">
     <div id="orb-container">
       <div id="orb-text-centered">
         <%= link_to planet.name, planet_path(planet.id) %>
       </div><!-- END of orb-text-centered DIV -->

      <% if planet.image == nil || planet.image.empty? %>
          <div id="empty-orb"></div>
      <% end %>

      <% if planet.name == 'Saturn' %>
          <%= link_to image_tag(planet.image, :alt => planet.name, :class => 'saturn'), planet_path(planet.id) %>
      <% end %>

      <% unless planet.image == nil || planet.image.empty? || planet.name == 'Saturn' %>
          <%= link_to image_tag(planet.image, :alt => planet.name, :class => 'planet'), planet_path(planet.id) %>
      <% end %>
    </div><!-- END of orb-container DIV -->
  </p><!-- END of planet-index P tag -->
  <% end %>
</aside>

<% if @current_user.present? %>
 <div class="controls new-planet">
   <h3><%= link_to 'New Planet', new_planet_path %></h3>
 </div>
<% end %>

app/views/planets/new.html.erb
<h1>New Planet</h1>

<%= render 'form', planet: @planet %>

<div class="controls">
  <%= link_to 'Back', planets_path %>
</div>
<%# link_to 'Home', home_path %>

app/views/planets/show.html.erb
<p id="notice"><%= notice %></p>

<% unless @planet.image == nil || @planet.image.empty? %>
  <%= link_to image_tag(@planet.image, :alt => @planet.name, :class => 'thumb'), @planet.image %>
<% end %>

<div class="show-text">
  <h2><%= @planet.name %></h2>
  <p>
    <strong><%= @planet.name %> radius</strong>
    <%= @planet.radius_planet %> km
  </p>

  <p>
    <strong>Number of moons </strong>
    <%= @planet.num_moon %>
  </p>

  <% @planet.moons.each do |moon| %>
    <li><%= link_to moon.name, moon %></li>
  <% end %>

  <p>
    <strong>Distance from sun</strong>
    <%= @planet.distance_sun %> million km
  </p>

  <p>
    <% if @planet.name == 'Earth' %>
      <strong>Time taken to orbit the sun</strong>
      <%= (@planet.orbit_sun).round %> year
    <% else %>
      <strong>Time taken to orbit the sun</strong>
      <%= @planet.orbit_sun %> Earth years
    <% end %>
  </p>

  <p id="wikioutput">
    <%= simple_format(@planet.info) %>
  </p>

</div><!-- END show-text DIV -->

<% if @current_user.present? %>
  <div class="controls">
    <%= link_to 'Edit planet', edit_planet_path(@planet) %>
    <!-- <%# link_to 'New planet', new_planet_path %> | -->
    <% if @current_user.admin %>
      | <%= link_to 'Delete planet', @planet, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
    <% end %>
  </div>
<% end %>