config/routes.rb
# == Route Map
#
#      Prefix Verb   URI Pattern                 Controller#Action
#       moons GET    /moons(.:format)            moons#index
#             POST   /moons(.:format)            moons#create
#    new_moon GET    /moons/new(.:format)        moons#new
#   edit_moon GET    /moons/:id/edit(.:format)   moons#edit
#        moon GET    /moons/:id(.:format)        moons#show
#             PATCH  /moons/:id(.:format)        moons#update
#             PUT    /moons/:id(.:format)        moons#update
#             DELETE /moons/:id(.:format)        moons#destroy
#     planets GET    /planets(.:format)          planets#index
#             POST   /planets(.:format)          planets#create
#  new_planet GET    /planets/new(.:format)      planets#new
# edit_planet GET    /planets/:id/edit(.:format) planets#edit
#      planet GET    /planets/:id(.:format)      planets#show
#             PATCH  /planets/:id(.:format)      planets#update
#             PUT    /planets/:id(.:format)      planets#update
#             DELETE /planets/:id(.:format)      planets#destroy
#       users GET    /users(.:format)            users#index
#             POST   /users(.:format)            users#create
#    new_user GET    /users/new(.:format)        users#new
#   edit_user GET    /users/:id/edit(.:format)   users#edit
#        user GET    /users/:id(.:format)        users#show
#             PATCH  /users/:id(.:format)        users#update
#             PUT    /users/:id(.:format)        users#update
#             DELETE /users/:id(.:format)        users#destroy
#

Rails.application.routes.draw do
  root :to => 'pages#home' # same as localhost 3000

  resources :users, :only => [:new, :create]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :moons
  resources :planets
  resources :users


  # post 'planets/:id/edit' => 'planets#add_moon'
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/moon.rb
# == Schema Information
#
# Table name: moons
#
#  id                  :integer          not null, primary key
#  name                :text
#  distance_planet     :float
#  radius_orbit_planet :float
#  radius_moon         :float
#  orbit_planet        :float
#  image               :text
#  info                :text
#  planet_id           :integer
#  user_id             :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Moon < ApplicationRecord
  belongs_to :planet
end

app/controllers/moons_controller.rb
class MoonsController < ApplicationController
  before_action :set_moon, only: [:show, :edit, :update, :destroy]


  # GET /moons
  # GET /moons.json
  def index
    @moons = Moon.all
  end

  # GET /moons/1
  # GET /moons/1.json
  def show
    @moon = Moon.find params[:id]
    @planet = @moon.planet
  end

  # GET /moons/new
  def new
    @moon = Moon.new
  end

  # GET /moons/1/edit
  def edit
    @moon = Moon.find params[:id]
  end

  # POST /moons
  # POST /moons.json
  def create
    @moon = Moon.new(moon_params)


    if params['moon']['image'].nil?
    else
         # perform file upload
         cloudinary = Cloudinary::Uploader.upload( params['moon']['image'])
         @moon.image = cloudinary['url']
    end

    respond_to do |format|
      if @moon.save
        format.html { redirect_to @moon, notice: 'Moon was successfully created.' }
        format.json { render :show, status: :created, location: @moon }
      else
        format.html { render :new }
        format.json { render json: @moon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moons/1
  # PATCH/PUT /moons/1.json
  def update
    if params['moon']['image'].nil?
    else
         # perform file upload
         cloudinary = Cloudinary::Uploader.upload( params['moon']['image'])
         @moon.image = cloudinary['url']
    end

    respond_to do |format|
      if @moon.update(moon_params)
        format.html { redirect_to @moon, notice: 'Moon was successfully updated.' }
        format.json { render :show, status: :ok, location: @moon }
      else
        format.html { render :edit }
        format.json { render json: @moon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moons/1
  # DELETE /moons/1.json
  def destroy
    @moon.destroy
    respond_to do |format|
      format.html { redirect_to moons_url, notice: 'Moon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_moon
      @moon = Moon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def moon_params
      params.require(:moon).permit(:name, :distance_planet, :radius_orbit_planet, :radius_moon, :orbit_planet, :info, :planet_id, :user_id)
    end
end

app/helpers/moons_helper.rb
module MoonsHelper
end

app/views/moons/_form.html.erb
<div class="form-style">
  <%= form_for @moon, :html => { :multipart => true } do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, :autofocus => true %>

      <%= f.label :distance_planet %>
      <%= f.text_field :distance_planet, :autofocus => true %>

      <%= f.label :radius_moon %>
      <%= f.text_field :radius_moon, :autofocus => true %>

      <%= f.label :orbit_planet %>
      <%= f.text_field :orbit_planet, :autofocus => true %>

      <%= f.label :image %>
      <%= f.file_field :image %>

      <%= f.label :info %>
      <%= f.text_area :info, :autofocus => true, :class => 'notes-text-area' %>

      <h3>Add Planet</h3>
      <%= label_tag :name %>
      <%= f.select :planet_id, Planet.pluck(:name, :id), :include_blank => true %>

      <%= f.submit %>
    <% end %>
</div><!-- END form-style DIV -->

app/views/moons/edit.html.erb
<h1>Editing Moon</h1>

<%# render 'form', moon: @moon %>
<%= render :partial => 'form' %>

<div class="controls">
  <%= link_to 'Show', @moon %> |
  <%= link_to 'Back', moons_path %>
</div>

app/views/moons/index.html.erb
<p id="notice"><%= notice %></p>

  <h2 id="show-moon-h2">Moons</h2>

<% @moons.each do |moon| %>
  <p id="moon-index">
    <div id="orb-container">
      <div id="orb-text-centered">

        <%= link_to moon.name, moon_path(moon.id) %>
      </div><!-- END of orb-text-centered DIV -->
      <% if moon.image == nil || moon.image.empty? %>
        <div id="empty-orb"></div>
      <% else %>
        <%= link_to image_tag(moon.image, :alt => moon.name, :class => 'moon'), moon_path(moon.id) %>
      <% end %>
    </div><!-- END of orb-container DIV -->
  </p><!-- END of moon-index P tag -->
<% end %>

<% if @current_user.present? %>
<div class="controls new-moon">
  <h3><%= link_to 'New Moon', new_moon_path %></h3>
</div>
<% end %>

app/views/moons/new.html.erb
<h1>New Moon</h1>

<%= render 'form', moon: @moon %>

<div class="controls">
  <%= link_to 'Back', moons_path %>
</div>

app/views/moons/show.html.erb
<p id="notice"><%= notice %></p>

<% unless @moon.image == nil || @moon.image.empty? %>
  <%= link_to image_tag(@moon.image, :alt => @moon.name, :class => 'thumb'), @moon.image %>
<% end %>

<div class="show-text">
  <h2><%= @moon.name %></h2>
  <p>
    <strong><%= @moon.name %> radius</strong>
    <%= @moon.radius_moon %> km
  </p>

  <p>
    <strong>Orbits planet </strong>
    <%= link_to @moon.planet.name, planet_path(@planet) %>
  </p>

  <p>
    <strong>Distance from <%= @moon.planet.name %></strong>
    <%= @moon.distance_planet %> km
  </p>

  <p>
    <% if @moon.orbit_planet %>
      <strong>Time taken to orbit <%= @moon.planet.name %></strong>
      <%= (@moon.orbit_planet).round %> Earth hours
    <% end %>
  </p>

  <p id="wikioutput">
    <%= simple_format(@moon.info) %>
  </p>
</div><!-- END show-text DIV -->

<% if @current_user.present? %>
  <div class="controls">
    <%= link_to 'Edit moon', edit_moon_path(@moon) %>
    <% if @current_user.admin %>
      | <%= link_to 'Delete moon', @moon, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
    <% end %>
  </div>
<% end %>